// Code generated by hinge gen. DO NOT EDIT.
// Enterpoint 守卫与端点表：路径↔函数对应关系的唯一检视入口。

package eps

import (
	"github.com/EdSan845D/oapi-hinge/hinge"
)
var _ hinge.Enterpoint = FileEp{}

// Enterpoint 标记实现（hinge gen 生成）。
func (FileEp) Enterpoint() {}

// Endpoints 路径↔函数对应关系表（openapi 文档与一致性测试的消费源）。
func (FileEp) Endpoints() []hinge.Endpoint {
	return []hinge.Endpoint{
		{
			Owner:   "FileEp",
			Handler: "DownloadSample",
			Method:  "GET",
			Path:    "/files/{name}",
			Summary: "下载示例文件（FileStream 二进制流响应）",
			Tags: []string{"文件"},
			QType: hinge.Type[DownloadSampleReq](),
			RType: hinge.Type[*hinge.FileStream](),
		},
	}
}

var _ hinge.Enterpoint = SystemEp{}

// Enterpoint 标记实现（hinge gen 生成）。
func (SystemEp) Enterpoint() {}

// Endpoints 路径↔函数对应关系表（openapi 文档与一致性测试的消费源）。
func (SystemEp) Endpoints() []hinge.Endpoint {
	return []hinge.Endpoint{
		{
			Owner:   "SystemEp",
			Handler: "Health",
			Method:  "GET",
			Path:    "/health",
			Summary: "健康检查",
			RType: hinge.Type[map[string]string](),
		},
	}
}

var _ hinge.Enterpoint = UserEp{}

// Enterpoint 标记实现（hinge gen 生成）。
func (UserEp) Enterpoint() {}

// Endpoints 路径↔函数对应关系表（openapi 文档与一致性测试的消费源）。
func (UserEp) Endpoints() []hinge.Endpoint {
	return []hinge.Endpoint{
		{
			Owner:   "UserEp",
			Handler: "ChangePassword",
			Method:  "PATCH",
			Path:    "/users/{id}/password",
			Summary: "修改密码（出参脱敏演示：InTransform 规范化 + validate 标签 + OutTransform）",
			Tags: []string{"用户"},
			Auth: "BearerAuth",
			QType: hinge.Type[ChangePasswordReq](),
			RType: hinge.Type[MaskedUser](),
		},
		{
			Owner:   "UserEp",
			Handler: "CreateUser",
			Method:  "POST",
			Path:    "/users",
			Summary: "创建用户",
			Tags: []string{"用户"},
			Status: 201,
			Auth: "BearerAuth",
			BType: hinge.Type[CreateUserReq](),
			RType: hinge.Type[User](),
		},
		{
			Owner:   "UserEp",
			Handler: "DeleteUser",
			Method:  "DELETE",
			Path:    "/users/{id}",
			Summary: "删除用户（Empty 响应：data 为 null）",
			Tags: []string{"用户"},
			Auth: "BearerAuth",
			QType: hinge.Type[DeleteUserReq](),
			RType: hinge.Type[hinge.Empty](),
		},
		{
			Owner:   "UserEp",
			Handler: "GetUser",
			Method:  "GET",
			Path:    "/users/{id}",
			Summary: "用户详情",
			Tags: []string{"用户"},
			Auth: "BearerAuth",
			QType: hinge.Type[GetUserReq](),
			RType: hinge.Type[User](),
		},
		{
			Owner:   "UserEp",
			Handler: "ListUsers",
			Method:  "GET",
			Path:    "/users",
			Summary: "用户列表（分页）",
			Tags: []string{"用户"},
			Auth: "BearerAuth",
			QType: hinge.Type[ListUsersReq](),
			RType: hinge.Type[hinge.Paged[User]](),
		},
	}
}

