#!/usr/bin/env bash
# oapi-hinge 统一测试入口：全仓 build + vet + test（openapi 走 -tags openapi）
# 用法：./test.sh
set -e
cd "$(dirname "$0")"

echo "=== 默认构建（release 语义，不含 openapi 包） ==="
go build ./...
go vet ./...
go test ./...

echo "=== openapi（-tags openapi） ==="
go build -tags openapi ./...
go vet -tags openapi ./...
go test -tags openapi ./...

echo "ALL PASS"
