// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=./app/eps,./app/middleware）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen

package apigen

import (
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	"github.com/EdSan845D/oapi-hinge/hinge"
	"github.com/gin-gonic/gin"
)
// All 聚合全部 Enterpoint 实例（字段名 = 结构体名）。
type All struct {
	FileEp eps.FileEp
	SystemEp eps.SystemEp
	UserEp eps.UserEp
}

// RegisterAllGin 一次装配全部端点（servergin）。
func RegisterAllGin(r gin.IRouter, k *hinge.Kernel, all All) {
	RegisterFileEpGin(r, k, all.FileEp)
	RegisterPKG_epsGin(r, k)
	RegisterSystemEpGin(r, k, all.SystemEp)
	RegisterUserEpGin(r, k, all.UserEp)
}

