// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=example/app/eps）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen

package apigen

import (
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	"github.com/EdSan845D/oapi-hinge/hinge"
	"github.com/gin-gonic/gin"
	"github.com/labstack/echo/v4"
	"net/http"
)
// All 聚合全部 Enterpoint 实例（字段名 = 结构体名）。
type All struct {
	FileEp eps.FileEp
	SystemEp eps.SystemEp
	UserEp eps.UserEp
}

// RegisterAllGin 一次装配全部端点（servergin）。
func RegisterAllGin(r gin.IRouter, k *hinge.Kernel, all All) {
	RegisterFileEpGin(r, k, all.FileEp)
	RegisterSystemEpGin(r, k, all.SystemEp)
	RegisterUserEpGin(r, k, all.UserEp)
}

// RegisterAllEcho 一次装配全部端点（serverecho）。
func RegisterAllEcho(r echo.Router, k *hinge.Kernel, all All) {
	RegisterFileEpEcho(r, k, all.FileEp)
	RegisterSystemEpEcho(r, k, all.SystemEp)
	RegisterUserEpEcho(r, k, all.UserEp)
}

// RegisterAllHTTP 一次装配全部端点（serverhttp）。
func RegisterAllHTTP(r *http.ServeMux, k *hinge.Kernel, all All) {
	RegisterFileEpHTTP(r, k, all.FileEp)
	RegisterSystemEpHTTP(r, k, all.SystemEp)
	RegisterUserEpHTTP(r, k, all.UserEp)
}

