// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=example/app/eps）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen

package apigen

import (
	"context"
	"fmt"
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	"github.com/EdSan845D/oapi-hinge/hinge"
	"time"
)
func BindBCreateUserReq(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.CreateUserReq
	be := &hinge.BindError{}
	add := be.AddField
	data, err := r.Body()
	if err != nil {
		return v, err
	}
	if len(data) > 0 {
		if err := hinge.DecodeJSON(data, &v); err != nil {
			if be2 := hinge.AsBindError(err); be2 != nil {
				return v, be2
			}
			return v, err
		}
		if err := (&v).InTransform(ctx); err != nil {
			return v, err
		}
	}
	if v.Name == "" {
		add("name", "body", "is required")
	}
	if v.Email == "" {
		add("email", "body", "is required")
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	if err := v.Validate(); err != nil {
		return v, fmt.Errorf("validate failed: %w", err)
	}
	return v, nil
}

func BindBExtraBody(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.ExtraBody
	be := &hinge.BindError{}
	add := be.AddField
	_ = add
	data, err := r.Body()
	if err != nil {
		return v, err
	}
	if len(data) > 0 {
		if err := hinge.DecodeJSON(data, &v); err != nil {
			if be2 := hinge.AsBindError(err); be2 != nil {
				return v, be2
			}
			return v, err
		}
	}
	return v, nil
}

func BindQChangePasswordReq(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.ChangePasswordReq
	be := &hinge.BindError{}
	add := be.AddField
	if raw, ok := r.PathParam("id"); ok {
		x, err := hinge.Parse[string](raw, "id")
		if err != nil {
			add("id", "path", err.Error())
		} else {
		v.ID = x
		}
	}
	if vals, ok := r.QueryValues("password"); ok && len(vals) > 0 && vals[0] != "" {
		x, err := hinge.Parse[string](vals[0], "password")
		if err != nil {
			add("password", "query", err.Error())
		} else {
		v.Password = x
		}
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	if err := (&v).InTransform(ctx); err != nil {
		return v, err
	}
	if v.Password == "" {
		add("password", "query", "is required")
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	return v, nil
}

func BindQDeleteUserReq(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.DeleteUserReq
	be := &hinge.BindError{}
	add := be.AddField
	if raw, ok := r.PathParam("id"); ok {
		x, err := hinge.Parse[string](raw, "id")
		if err != nil {
			add("id", "path", err.Error())
		} else {
		v.ID = x
		}
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	return v, nil
}

func BindQDownloadSampleReq(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.DownloadSampleReq
	be := &hinge.BindError{}
	add := be.AddField
	if raw, ok := r.PathParam("name"); ok {
		x, err := hinge.Parse[string](raw, "name")
		if err != nil {
			add("name", "path", err.Error())
		} else {
		v.Name = x
		}
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	return v, nil
}

func BindQGetUserReq(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.GetUserReq
	be := &hinge.BindError{}
	add := be.AddField
	if raw, ok := r.PathParam("id"); ok {
		x, err := hinge.Parse[string](raw, "id")
		if err != nil {
			add("id", "path", err.Error())
		} else {
		v.ID = x
		}
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	return v, nil
}

func BindQListUsersReq(ctx context.Context, r hinge.RequestReader) (any, error) {
	var v eps.ListUsersReq
	be := &hinge.BindError{}
	add := be.AddField
	if vals, ok := r.QueryValues("page"); ok && len(vals) > 0 && vals[0] != "" {
		x, err := hinge.Parse[int](vals[0], "page")
		if err != nil {
			add("page", "query", err.Error())
		} else {
		v.PageQuery.Page = x
		}
	}
	if v.PageQuery.Page == 0 {
		x, err := hinge.Parse[int]("1", "page")
		if err != nil {
			add("page", "query", err.Error())
		} else {
		v.PageQuery.Page = x
		}
	}
	if vals, ok := r.QueryValues("size"); ok && len(vals) > 0 && vals[0] != "" {
		x, err := hinge.Parse[int](vals[0], "size")
		if err != nil {
			add("size", "query", err.Error())
		} else {
		v.PageQuery.Size = x
		}
	}
	if v.PageQuery.Size == 0 {
		x, err := hinge.Parse[int]("10", "size")
		if err != nil {
			add("size", "query", err.Error())
		} else {
		v.PageQuery.Size = x
		}
	}
	if vals, ok := r.QueryValues("since"); ok && len(vals) > 0 && vals[0] != "" {
		x, err := hinge.Parse[time.Time](vals[0], "since")
		if err != nil {
			add("since", "query", err.Error())
		} else {
		v.Since = x
		}
	}
	if len(be.Fields) > 0 {
		return v, be
	}
	return v, nil
}

