// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=./app/eps,./app/middleware）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen
// entrypoints: programmatic（本仓库使用程序化 EntryPoint 配置，CLI gen/-check 已禁止；请用项目内生成入口）

package apigen

import (
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	"github.com/EdSan845D/oapi-hinge/hinge"
)

func AllDocSpecs() []hinge.EndpointDoc {
	return []hinge.EndpointDoc{
		DocSpecAdminEpIndex(),
		DocSpecAuditEpListEvents(),
		DocSpecFileEpDownloadSample(),
		DocSpecPKG_epsIndex(),
		DocSpecSystemEpHealth(),
		DocSpecUserEpChangePassword(),
		DocSpecUserEpCreateUser(),
		DocSpecUserEpDeleteUser(),
		DocSpecUserEpGetUser(),
		DocSpecUserEpListUsers(),
		DocSpecUserEpUpdateExtra(),
	}
}
func DocSpecAdminEpIndex() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint:    SpecAdminEpIndex(),
		Summary:     "Index 组根路由：oapi:route 省路径即组根（/admin）。",
		Description: "管理面板索引",
		Tags:        []string{"管理"},
		MWRefs:      []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		RType:       hinge.Type[map[string]string](),
	}
}

func DocSpecAuditEpListEvents() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecAuditEpListEvents(),
		Summary:  "审计事件列表(两级挂载演示:/admin(父挂载点)+ /audit(本节点挂载点)+ /events)",
		Tags:     []string{"审计"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.AccessLog"},
		QType:    hinge.Type[eps.AuditQ](),
		RType:    hinge.Type[eps.Paged[eps.AuditEvent]](),
	}
}

func DocSpecFileEpDownloadSample() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecFileEpDownloadSample(),
		Summary:  "下载示例文件（FileStream 二进制流响应）",
		Tags:     []string{"文件"},
		QType:    hinge.Type[eps.DownloadSampleReq](),
		RType:    hinge.Type[*hinge.FileStream](),
	}
}

func DocSpecPKG_epsIndex() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecPKG_epsIndex(),
		Summary:  "Index",
		RType:    hinge.Type[string](),
	}
}

func DocSpecSystemEpHealth() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint:    SpecSystemEpHealth(),
		Summary:     "健康检查（代码覆写示例）",
		Description: "描述由 EntryPointConfig.FuncDecls 程序化覆写：非零字段覆盖注解值，生成日志会打印覆写提示。",
		Deprecated:  true,
		MWRefs:      []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		RType:       hinge.Type[map[string]string](),
	}
}

func DocSpecUserEpChangePassword() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecUserEpChangePassword(),
		Summary:  "修改密码（出参脱敏演示：InTransform 规范化 + validate 标签 + OutTransform）",
		Tags:     []string{"用户"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		QType:    hinge.Type[eps.ChangePasswordReq](),
		RType:    hinge.Type[eps.MaskedUser](),
	}
}

func DocSpecUserEpCreateUser() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecUserEpCreateUser(),
		Summary:  "创建用户",
		Tags:     []string{"用户"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		BType:    hinge.Type[eps.CreateUserReq](),
		RType:    hinge.Type[eps.User](),
	}
}

func DocSpecUserEpDeleteUser() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecUserEpDeleteUser(),
		Summary:  "删除用户（Empty 响应：data 为 null）",
		Tags:     []string{"用户"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth", "github.com/EdSan845D/oapi-hinge/example/app/middleware.ParseHeaderWithInfo"},
		QType:    hinge.Type[eps.DeleteUserReq](),
		RType:    hinge.Type[hinge.Empty](),
	}
}

func DocSpecUserEpGetUser() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecUserEpGetUser(),
		Summary:  "用户详情",
		Tags:     []string{"用户"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		QType:    hinge.Type[eps.GetUserReq](),
		RType:    hinge.Type[eps.User](),
	}
}

func DocSpecUserEpListUsers() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecUserEpListUsers(),
		Summary:  "用户列表（分页）",
		Tags:     []string{"用户"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		QType:    hinge.Type[eps.ListUsersReq](),
		RType:    hinge.Type[eps.Paged[eps.User]](),
	}
}

func DocSpecUserEpUpdateExtra() hinge.EndpointDoc {
	return hinge.EndpointDoc{
		Endpoint: SpecUserEpUpdateExtra(),
		Summary:  "修改用户扩展信息（演示 any 类型的请求体绑定）",
		Tags:     []string{"用户"},
		MWRefs:   []string{"github.com/EdSan845D/oapi-hinge/example/app/middleware.Auth"},
		QType:    hinge.Type[eps.GetUserReq](),
		BType:    hinge.Type[eps.ExtraBody](),
		RType:    hinge.Type[eps.User](),
	}
}
