// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=example/app/eps）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen

package apigen

import (
	"context"
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	"github.com/EdSan845D/oapi-hinge/hinge"
	"github.com/EdSan845D/oapi-hinge/serverhttp"
	"net/http"
)
// RegisterFileEpHTTP 把 FileEp 的全部端点挂到 http。
func RegisterFileEpHTTP(r *http.ServeMux, k *hinge.Kernel, ep eps.FileEp) {
	r.HandleFunc("GET /files/{name}", serverhttp.Handle(k, specFileEpDownloadSample, bindQDownloadSampleReq, nil, func(ctx context.Context, q, b any) (any, error) {
			return ep.DownloadSample(ctx, q.(eps.DownloadSampleReq))
		}))
}

// RegisterSystemEpHTTP 把 SystemEp 的全部端点挂到 http。
func RegisterSystemEpHTTP(r *http.ServeMux, k *hinge.Kernel, ep eps.SystemEp) {
	r.HandleFunc("GET /health", serverhttp.Handle(k, specSystemEpHealth, nil, nil, func(ctx context.Context, q, b any) (any, error) {
			return ep.Health(ctx, q)
		}))
}

// RegisterUserEpHTTP 把 UserEp 的全部端点挂到 http。
func RegisterUserEpHTTP(r *http.ServeMux, k *hinge.Kernel, ep eps.UserEp) {
	r.HandleFunc("PATCH /users/{id}/password", serverhttp.Handle(k, specUserEpChangePassword, bindQChangePasswordReq, nil, func(ctx context.Context, q, b any) (any, error) {
			return ep.ChangePassword(ctx, q.(eps.ChangePasswordReq))
		}))
	r.HandleFunc("POST /users", serverhttp.Handle(k, specUserEpCreateUser, nil, bindBCreateUserReq, func(ctx context.Context, q, b any) (any, error) {
			return ep.CreateUser(ctx, q, b.(eps.CreateUserReq))
		}))
	r.HandleFunc("DELETE /users/{id}", serverhttp.Handle(k, specUserEpDeleteUser, bindQDeleteUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
			return ep.DeleteUser(ctx, q.(eps.DeleteUserReq))
		}))
	r.HandleFunc("GET /users/{id}", serverhttp.Handle(k, specUserEpGetUser, bindQGetUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
			return ep.GetUser(ctx, q.(eps.GetUserReq))
		}))
	r.HandleFunc("GET /users", serverhttp.Handle(k, specUserEpListUsers, bindQListUsersReq, nil, func(ctx context.Context, q, b any) (any, error) {
			return ep.ListUsers(ctx, q.(eps.ListUsersReq))
		}))
}

