// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=./app/eps,./app/middleware）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen
// entrypoints: programmatic（本仓库使用程序化 EntryPoint 配置，CLI gen/-check 已禁止；请用项目内生成入口）

package apigen

import (
	"context"
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	middleware "github.com/EdSan845D/oapi-hinge/example/app/middleware"
	"github.com/EdSan845D/oapi-hinge/hinge"
	"io"
	"mime/multipart"
	"net/http"

	"github.com/gin-gonic/gin"
)

type Reader struct {
	C *gin.Context
}

func (r *Reader) Context() context.Context { return r.C.Request.Context() }

func (r *Reader) Method() string { return r.C.Request.Method }

func (r *Reader) PathParam(name string) (string, bool) {
	v := r.C.Param(name)
	return v, v != ""
}

func (r *Reader) QueryValues(name string) ([]string, bool) {
	vals := r.C.QueryArray(name)
	return vals, len(vals) > 0
}

func (r *Reader) FormValues(name string) ([]string, bool) {
	if err := r.C.Request.ParseForm(); err != nil {
		return nil, false
	}
	vals := r.C.Request.PostForm[name]
	return vals, len(vals) > 0
}

func (r *Reader) Header(name string) (string, bool) {
	v := r.C.GetHeader(name)
	return v, v != ""
}

func (r *Reader) Cookie(name string) (string, bool) {
	v, err := r.C.Cookie(name)
	if err != nil || v == "" {
		return "", false
	}
	return v, true
}

func (r *Reader) Body() ([]byte, error) {
	if r.C.Request.Body == nil {
		return nil, nil
	}
	return io.ReadAll(r.C.Request.Body)
}

func (r *Reader) MultipartForm() (*multipart.Form, error) {
	// 标准库对已解析请求为空操作；内存缓冲水位固定 32MB
	if err := r.C.Request.ParseMultipartForm(32 << 20); err != nil {
		return nil, err
	}
	return r.C.Request.MultipartForm, nil
}

// Sink hinge.Sink 实现（拦截器短路写出口径）：written 标志防短路后重复输出。
type Sink struct {
	C       *gin.Context
	written bool
}

func (s *Sink) SetStatus(code int)          { s.C.Status(code) }
func (s *Sink) SetHeader(k, v string)       { s.C.Header(k, v) }
func (s *Sink) AddCookie(c *http.Cookie)    { http.SetCookie(s.C.Writer, c) }
func (s *Sink) WriteJSON(status int, v any) { s.written = true; s.C.JSON(status, v) }

// WriteStream 二进制流（FileStream）：row 模板的极简形态不做 Range/条件请求，
// 复制 Reader 全量输出；需要 Range 语义请用内置模板（内核 writeStreamFile）。
func (s *Sink) WriteStream(f *hinge.FileStream) {
	if f == nil || f.Reader == nil {
		s.C.String(http.StatusInternalServerError, "invalid file stream")
		return
	}
	s.written = true
	if f.ContentType != "" {
		s.C.Header("Content-Type", f.ContentType)
	}
	s.C.Status(http.StatusOK)
	_, _ = io.Copy(s.C.Writer, f.Reader)
}

// Adaptor 极简管线（row 模板自足形态）：绑定 + 内核拦截链 + 输出。
// 拦截链语义与内核 HandleWith 对齐：ICs 按声明序包裹（先根后叶的合成序由
// 发射器保证），短路拦截器经 Sink 自行写出（written 防重复输出）；
// 返回错误走 500。
func Adaptor(ep hinge.Endpoint, bindQ hinge.Binder, bindB hinge.Binder, h hinge.HandlerFunc, ics ...hinge.Interceptor) gin.HandlerFunc {
	return func(c *gin.Context) {
		var qv, bv any
		if bindQ != nil {
			v, err := bindQ(c, &Reader{C: c})
			if err != nil {
				c.AbortWithError(http.StatusBadRequest, err)
				return
			}
			qv = v
		}
		if bindB != nil {
			v, err := bindB(c, &Reader{C: c})
			if err != nil {
				c.AbortWithError(http.StatusBadRequest, err)
				return
			}
			bv = v
		}
		rd := &Reader{C: c}
		sn := &Sink{C: c}
		var out any
		call := func(ctx context.Context) error {
			var err error
			out, err = h(ctx, qv, bv)
			return err
		}
		for i := len(ics) - 1; i >= 0; i-- {
			ic, next := ics[i], call
			call = func(ctx context.Context) error {
				return ic(ctx, ep, rd, sn, next)
			}
		}
		if err := call(c.Request.Context()); err != nil {
			c.AbortWithError(http.StatusInternalServerError, err)
			return
		}
		if !sn.written {
			c.JSON(http.StatusOK, out)
		}
	}
}

// RegisterAdminEpGinRow 把 AdminEp 的全部端点挂到 GinRow。
func RegisterAdminEpGinRow(i gin.IRouter, ep eps.AdminEp) {
	r := i.Group("", middleware.Auth)
	r.GET("/admin", Adaptor(hinge.Endpoint{Owner: "AdminEp", Handler: "Index", Method: "GET", Path: "/admin"}, nil, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.Index(ctx)
	}))
}

// RegisterAuditEpGinRow 把 AuditEp 的全部端点挂到 GinRow。
func RegisterAuditEpGinRow(i gin.IRouter, ep eps.AuditEp) {
	r := i.Group("", middleware.Auth)
	r.GET("/admin/audit/events", Adaptor(hinge.Endpoint{Owner: "AuditEp", Handler: "ListEvents", Method: "GET", Path: "/admin/audit/events"}, BindQAuditQ, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ListEvents(ctx, q.(eps.AuditQ))
	}, middleware.AccessLog))
}

// RegisterFileEpGinRow 把 FileEp 的全部端点挂到 GinRow。
func RegisterFileEpGinRow(i gin.IRouter, ep eps.FileEp) {
	r := i
	r.GET("/files/:name", Adaptor(hinge.Endpoint{Owner: "FileEp", Handler: "DownloadSample", Method: "GET", Path: "/files/:name"}, BindQDownloadSampleReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.DownloadSample(ctx, q.(eps.DownloadSampleReq))
	}))
}

// RegisterPKG_epsGinRow 把 PKG_eps 的全部端点挂到 GinRow。
func RegisterPKG_epsGinRow(i gin.IRouter) {
	r := i
	r.GET("/", Adaptor(hinge.Endpoint{Owner: "eps", Handler: "Index", Method: "GET", Path: "/"}, nil, nil, func(ctx context.Context, q, b any) (any, error) {
		return eps.Index(ctx, q)
	}))
}

// RegisterSystemEpGinRow 把 SystemEp 的全部端点挂到 GinRow。
func RegisterSystemEpGinRow(i gin.IRouter, ep eps.SystemEp) {
	r := i.Group("", middleware.Auth)
	r.GET("/health", Adaptor(hinge.Endpoint{Owner: "SystemEp", Handler: "Health", Method: "GET", Path: "/health"}, nil, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.Health(ctx)
	}))
}

// RegisterUserEpGinRow 把 UserEp 的全部端点挂到 GinRow。
func RegisterUserEpGinRow(i gin.IRouter, ep eps.UserEp) {
	r := i.Group("", middleware.Auth)
	r.PATCH("/users/:id/password", Adaptor(hinge.Endpoint{Owner: "UserEp", Handler: "ChangePassword", Method: "PATCH", Path: "/users/:id/password"}, BindQChangePasswordReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ChangePassword(ctx, q.(eps.ChangePasswordReq))
	}))
	r.POST("/users", Adaptor(hinge.Endpoint{Owner: "UserEp", Handler: "CreateUser", Method: "POST", Path: "/users"}, nil, BindBCreateUserReq, func(ctx context.Context, q, b any) (any, error) {
		return ep.CreateUser(ctx, q, b.(eps.CreateUserReq))
	}))
	r.DELETE("/users/:id", middleware.ParseHeaderWithInfo, Adaptor(hinge.Endpoint{Owner: "UserEp", Handler: "DeleteUser", Method: "DELETE", Path: "/users/:id"}, BindQDeleteUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.DeleteUser(ctx, q.(eps.DeleteUserReq))
	}))
	r.GET("/users/:id", Adaptor(hinge.Endpoint{Owner: "UserEp", Handler: "GetUser", Method: "GET", Path: "/users/:id"}, BindQGetUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.GetUser(ctx, q.(eps.GetUserReq))
	}))
	r.GET("/users", Adaptor(hinge.Endpoint{Owner: "UserEp", Handler: "ListUsers", Method: "GET", Path: "/users"}, BindQListUsersReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ListUsers(ctx, q.(eps.ListUsersReq))
	}))
	r.PUT("/users/:id/extra", Adaptor(hinge.Endpoint{Owner: "UserEp", Handler: "UpdateExtra", Method: "PUT", Path: "/users/:id/extra"}, BindQGetUserReq, BindBExtraBody, func(ctx context.Context, q, b any) (any, error) {
		return ep.UpdateExtra(ctx, q.(eps.GetUserReq), b.(eps.ExtraBody))
	}))
}

// RegisterVipUserEpGinRow 把 VipUserEp 的全部端点挂到 GinRow。
func RegisterVipUserEpGinRow(i gin.IRouter, ep eps.VipUserEp) {
	r := i.Group("", middleware.Auth)
	r.PATCH("/users/vip/:id/password", Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "ChangePassword", Method: "PATCH", Path: "/users/vip/:id/password"}, BindQChangePasswordReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ChangePassword(ctx, q.(eps.ChangePasswordReq))
	}))
	r.POST("/users/vip", Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "CreateUser", Method: "POST", Path: "/users/vip"}, nil, BindBCreateUserReq, func(ctx context.Context, q, b any) (any, error) {
		return ep.CreateUser(ctx, q, b.(eps.CreateUserReq))
	}))
	r.DELETE("/users/vip/:id", middleware.ParseHeaderWithInfo, Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "DeleteUser", Method: "DELETE", Path: "/users/vip/:id"}, BindQDeleteUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.DeleteUser(ctx, q.(eps.DeleteUserReq))
	}))
	r.GET("/users/vip/:id", Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "GetUser", Method: "GET", Path: "/users/vip/:id"}, BindQGetUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.GetUser(ctx, q.(eps.GetUserReq))
	}))
	r.GET("/users/vip/panel", Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "LevelContent", Method: "GET", Path: "/users/vip/panel"}, nil, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.LevelContent(ctx)
	}))
	r.GET("/users/vip", Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "ListUsers", Method: "GET", Path: "/users/vip"}, BindQListUsersReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ListUsers(ctx, q.(eps.ListUsersReq))
	}))
	r.PUT("/users/vip/:id/extra", Adaptor(hinge.Endpoint{Owner: "VipUserEp", Handler: "UpdateExtra", Method: "PUT", Path: "/users/vip/:id/extra"}, BindQGetUserReq, BindBExtraBody, func(ctx context.Context, q, b any) (any, error) {
		return ep.UpdateExtra(ctx, q.(eps.GetUserReq), b.(eps.ExtraBody))
	}))
}

// RegisterAllGinRow 一次装配全部端点（GinRow）。
func RegisterAllGinRow(i gin.IRouter, all All) {
	RegisterAdminEpGinRow(i, all.AdminEp)
	RegisterAuditEpGinRow(i, all.AuditEp)
	RegisterFileEpGinRow(i, all.FileEp)
	RegisterPKG_epsGinRow(i)
	RegisterSystemEpGinRow(i, all.SystemEp)
	RegisterUserEpGinRow(i, all.UserEp)
	RegisterVipUserEpGinRow(i, all.VipUserEp)
}
