// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=./app/eps,./app/middleware）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen

package apigen

import (
	"context"
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	middleware "github.com/EdSan845D/oapi-hinge/example/app/middleware"
	"github.com/EdSan845D/oapi-hinge/hinge"
	"io"
	"mime/multipart"
	"net/http"

	"github.com/gin-gonic/gin"
)

type Reader struct {
	C *gin.Context
}

func (r *Reader) Context() context.Context { return r.C.Request.Context() }

func (r *Reader) Method() string { return r.C.Request.Method }

func (r *Reader) PathParam(name string) (string, bool) {
	v := r.C.Param(name)
	return v, v != ""
}

func (r *Reader) QueryValues(name string) ([]string, bool) {
	vals := r.C.QueryArray(name)
	return vals, len(vals) > 0
}

func (r *Reader) FormValues(name string) ([]string, bool) {
	if err := r.C.Request.ParseForm(); err != nil {
		return nil, false
	}
	vals := r.C.Request.PostForm[name]
	return vals, len(vals) > 0
}

func (r *Reader) Header(name string) (string, bool) {
	v := r.C.GetHeader(name)
	return v, v != ""
}

func (r *Reader) Cookie(name string) (string, bool) {
	v, err := r.C.Cookie(name)
	if err != nil || v == "" {
		return "", false
	}
	return v, true
}

func (r *Reader) Body() ([]byte, error) {
	if r.C.Request.Body == nil {
		return nil, nil
	}
	return io.ReadAll(r.C.Request.Body)
}

func (r *Reader) MultipartForm() (*multipart.Form, error) {
	// 标准库对已解析请求为空操作；内存缓冲水位固定 32MB
	if err := r.C.Request.ParseMultipartForm(32 << 20); err != nil {
		return nil, err
	}
	return r.C.Request.MultipartForm, nil
}

func Adaptor(bindQ hinge.Binder, bindB hinge.Binder, h hinge.HandlerFunc) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var qv, bv any
		if bindQ != nil {
			v, err := bindQ(ctx, &Reader{C: ctx})
			if err != nil {
				ctx.AbortWithError(http.StatusBadRequest, err)
				return
			}
			qv = v
		}
		if bindB != nil {
			v, err := bindB(ctx, &Reader{C: ctx})
			if err != nil {
				ctx.AbortWithError(http.StatusBadRequest, err)
				return
			}
			bv = v
		}
		out, err := h(ctx, qv, bv)
		if err != nil {
			ctx.AbortWithError(http.StatusInternalServerError, err)
			return
		}
		ctx.JSON(http.StatusOK, out)
	}
}

// RegisterFileEpGinRow 把 FileEp 的全部端点挂到 GinRow。
func RegisterFileEpGinRow(i gin.IRouter, ep eps.FileEp) {
	r := i
	r.GET("/files/:name", Adaptor(BindQDownloadSampleReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.DownloadSample(ctx, q.(eps.DownloadSampleReq))
	}))
}

// RegisterPKG_epsGinRow 把 PKG_eps 的全部端点挂到 GinRow。
func RegisterPKG_epsGinRow(i gin.IRouter) {
	r := i
	r.GET("/", Adaptor(nil, nil, func(ctx context.Context, q, b any) (any, error) {
		return eps.Index(ctx, q)
	}))
}

// RegisterSystemEpGinRow 把 SystemEp 的全部端点挂到 GinRow。
func RegisterSystemEpGinRow(i gin.IRouter, ep eps.SystemEp) {
	r := i
	r.GET("/health", Adaptor(nil, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.Health(ctx, q)
	}))
}

// RegisterUserEpGinRow 把 UserEp 的全部端点挂到 GinRow。
func RegisterUserEpGinRow(i gin.IRouter, ep eps.UserEp) {
	r := i.Group("", middleware.Auth)
	r.PATCH("/users/:id/password", Adaptor(BindQChangePasswordReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ChangePassword(ctx, q.(eps.ChangePasswordReq))
	}))
	r.POST("/users", Adaptor(nil, BindBCreateUserReq, func(ctx context.Context, q, b any) (any, error) {
		return ep.CreateUser(ctx, q, b.(eps.CreateUserReq))
	}))
	r.DELETE("/users/:id", middleware.ParseHeaderWithInfo, Adaptor(BindQDeleteUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.DeleteUser(ctx, q.(eps.DeleteUserReq))
	}))
	r.GET("/users/:id", Adaptor(BindQGetUserReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.GetUser(ctx, q.(eps.GetUserReq))
	}))
	r.GET("/users", Adaptor(BindQListUsersReq, nil, func(ctx context.Context, q, b any) (any, error) {
		return ep.ListUsers(ctx, q.(eps.ListUsersReq))
	}))
	r.PUT("/users/:id/extra", Adaptor(BindQGetUserReq, BindBExtraBody, func(ctx context.Context, q, b any) (any, error) {
		return ep.UpdateExtra(ctx, q.(eps.GetUserReq), b.(eps.ExtraBody))
	}))
}

// RegisterAllGinRow 一次装配全部端点（GinRow）。
func RegisterAllGinRow(i gin.IRouter, all All) {
	RegisterFileEpGinRow(i, all.FileEp)
	RegisterPKG_epsGinRow(i)
	RegisterSystemEpGinRow(i, all.SystemEp)
	RegisterUserEpGinRow(i, all.UserEp)
}
