// Code generated by hinge gen. DO NOT EDIT.
// 源：oapi:* 注解端点（scan=./app/eps,./app/middleware）
// 重新生成：go run github.com/EdSan845D/oapi-hinge/cmd/hinge gen
// entrypoints: programmatic（本仓库使用程序化 EntryPoint 配置，CLI gen/-check 已禁止；请用项目内生成入口）

package apigen

import (
	eps "github.com/EdSan845D/oapi-hinge/example/app/eps"
	"github.com/EdSan845D/oapi-hinge/hinge"
)

func AllSpecs() []hinge.Endpoint {
	return []hinge.Endpoint{
		SpecAdminEpIndex(),
		SpecAuditEpListEvents(),
		SpecFileEpDownloadSample(),
		SpecPKG_epsIndex(),
		SpecSystemEpHealth(),
		SpecUserEpChangePassword(),
		SpecUserEpCreateUser(),
		SpecUserEpDeleteUser(),
		SpecUserEpGetUser(),
		SpecUserEpListUsers(),
		SpecUserEpUpdateExtra(),
	}
}

// All 聚合全部 Enterpoint 实例（字段名 = 结构体名）。
type All struct {
	AdminEp  eps.AdminEp
	AuditEp  eps.AuditEp
	FileEp   eps.FileEp
	SystemEp eps.SystemEp
	UserEp   eps.UserEp
}

func SpecAdminEpIndex() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "AdminEp",
		Handler: "Index",
		Method:  "GET",
		Path:    "/admin",
	}
}

func SpecAuditEpListEvents() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "AuditEp",
		Handler: "ListEvents",
		Method:  "GET",
		Path:    "/admin/audit/events",
	}
}

func SpecFileEpDownloadSample() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "FileEp",
		Handler: "DownloadSample",
		Method:  "GET",
		Path:    "/files/{name}",
	}
}

func SpecPKG_epsIndex() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "PKG_eps",
		Handler: "Index",
		Method:  "GET",
		Path:    "/",
	}
}

func SpecSystemEpHealth() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "SystemEp",
		Handler: "Health",
		Method:  "GET",
		Path:    "/health",
	}
}

func SpecUserEpChangePassword() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "UserEp",
		Handler: "ChangePassword",
		Method:  "PATCH",
		Path:    "/users/{id}/password",
	}
}

func SpecUserEpCreateUser() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "UserEp",
		Handler: "CreateUser",
		Method:  "POST",
		Path:    "/users",
		Status:  201,
	}
}

func SpecUserEpDeleteUser() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "UserEp",
		Handler: "DeleteUser",
		Method:  "DELETE",
		Path:    "/users/{id}",
	}
}

func SpecUserEpGetUser() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "UserEp",
		Handler: "GetUser",
		Method:  "GET",
		Path:    "/users/{id}",
	}
}

func SpecUserEpListUsers() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "UserEp",
		Handler: "ListUsers",
		Method:  "GET",
		Path:    "/users",
	}
}

func SpecUserEpUpdateExtra() hinge.Endpoint {
	return hinge.Endpoint{
		Owner:   "UserEp",
		Handler: "UpdateExtra",
		Method:  "PUT",
		Path:    "/users/{id}/extra",
	}
}
